### ISSUE TITLE
Uncaught TypeError: Expecting valid order from block: body_attributes

### ISSUE THREAD

**Issue by Dheeraj87** [bwinf/blockly-html#1]
Hi,
After  I follow the steps which you have provided in the documentation, I'm getting the above error when demo.html page is loaded. What could be the issue?

**Comment by zgtm** [comment]
Should work again, now! Apparently, Blockly introduced that the orders of arithmetic operations are not allowed to be undefined values anymore … ;)

**Comment by HotdoGuy90** [comment]
Hi I have a function for a code block here:
```javascript
Blockly.Python.forBlock['base64_encode'] = function(block, generator) {
    var input = generator.valueToCode(block, "VALUE", Blockly.Python.ORDER_ADDITION) || '\'\''
    generator.definitions_['import_base64'] = 'import base64'
    var code = 'base64.b64encode(' + input + ')'
    return [code, Blockly.Python.ORDER_ADDITION]
}
```
I seem to be having problems with the Order Enum. I don't know which ones will help. The Javascript generator would work perfectly with that code (or the javascript code at least) but I guess the Python generator is much more strict. I can't find which Order works, being not used to having a strict generator.
