### ISSUE TITLE
u cant do anything in style tag

### ISSUE THREAD

**Issue by anowa-eng** [bwinf/blockly-html#2]
oh noes!
there's no `selector{}` block
now u can't do anything with `<style>`

i suggest
`
  "type": "eeeeeeg",
  "message0": "style of %1 %2 %3",
  "args0": [
    {
      "type": "field_input",
      "name": "selector",
      "text": "selector"
    },
    {
      "type": "input_dummy"
    },
    {
      "type": "input_statement",
      "name": "NAME"
    }
  ],
  "previousStatement": null,
  "nextStatement": null,
  "colour": 225,
  "tooltip": "",
  "helpUrl": ""
}`

**Comment by bestian** [comment]
how about {
  "type": "global_style",
  "message0": "selector %1 style %2",
  "args0": [
    {
      "type": "input_statement",
      "name": "selector",
      "check": "selector"
    },
    {
      "type": "input_statement",
      "name": "content",
      "check": "css"
    }
  ],
  "previousStatement": "header",
  "nextStatement": "header",
  "colour": 0,
  "tooltip": "",
  "helpUrl": "http://www.w3schools.com/tags/tag_html.asp"
}
?
